/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.hotelverwaltung.gui;

import com.mycompany.hotelverwaltung.persistence.Customer;
import com.mycompany.hotelverwaltung.persistence.PersistenceInterface;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Iterator;
import java.util.List;

/**
 *  JFrame used to edit a Customer.
 * @author Eddybrando, Felix Brass
 */
public class CustomersEdit extends javax.swing.JFrame {

    private final PersistenceInterface pi;
    private final String[] columnNames;
    private static final String WRONG_CALENDAR_FORMAT="Geburtstag muss im Format: tt.MM.jjjj sein";

    /**
     * Creates new form CustomersEdit
     * @param pi
     */
    public CustomersEdit(PersistenceInterface pi) {
        this.pi = pi;

        List<Customer> customersList = pi.getCustomerList();
        Iterator<Customer> it = customersList.iterator();
        String[] columnNames2 = {ANREDE, VORNAME, NACHNAME, GEBURTSTAG, STRAßE___NR, PLZ, STADT, LAND};
        this.columnNames = columnNames2;
        Object[][] data = new Object[customersList.size()][8];

        //fills JTable with data
        while (it.hasNext()) {
            Customer c = it.next();
            data[customersList.indexOf(c)][0] = c.getAdress();
            data[customersList.indexOf(c)][1] = c.getSurname();
            data[customersList.indexOf(c)][2] = c.getName();
            Calendar cal = c.getBirthday();
            SimpleDateFormat format1 = new SimpleDateFormat(DD_M_MYYYY);
            String formatted = format1.format(cal.getTime());
            data[customersList.indexOf(c)][3] = formatted;
            data[customersList.indexOf(c)][4] = c.getStreetnumber();
            data[customersList.indexOf(c)][5] = c.getZipcode();
            data[customersList.indexOf(c)][6] = c.getCity();
            data[customersList.indexOf(c)][7] = c.getCountry();
        }

        initComponents();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(data, columnNames2));

    }
    private static final String DD_M_MYYYY = "dd.MM.yyyy";
    private static final String LAND = "Land";
    private static final String STADT = "Stadt";
    private static final String PLZ = "PLZ";
    private static final String STRAßE___NR = "Straße & Nr.";
    private static final String GEBURTSTAG = "Geburtstag";
    private static final String NACHNAME = "Nachname";
    private static final String VORNAME = "Vorname";
    private static final String ANREDE = "Anrede";

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        editCustomer = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Kundendaten ändern - B&V Hotels");
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(33, 100, 155));

        jPanel3.setBackground(new java.awt.Color(22, 76, 136));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("KUNDENDATEN ÄNDERN");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(15, 15, 15))
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        editCustomer.setBackground(new java.awt.Color(255, 255, 255));
        editCustomer.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        editCustomer.setForeground(new java.awt.Color(22, 76, 136));
        editCustomer.setText("Änderungen speichern");
        editCustomer.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        editCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editCustomerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 780, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        exitButton.setBackground(new java.awt.Color(187, 187, 187));
        exitButton.setText("Beenden");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        back.setBackground(new java.awt.Color(187, 187, 187));
        back.setText("« zurück");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(exitButton)
                .addGap(41, 41, 41))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(exitButton))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(868, 489));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitButtonActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        dispose();
        CustomersManagement s = new CustomersManagement(pi);
        s.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * sets every Value for every Customer new.
     * @param evt 
     */
    private void editCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editCustomerActionPerformed

        int currentRow = 0;

        List<Customer> customersList = pi.getCustomerList();
        Iterator<Customer> it = customersList.iterator();

        while (it.hasNext()) {
            try {
                Customer c = it.next();
                c.setAdress((String) jTable1.getValueAt(currentRow, 0));
                c.setSurname((String) jTable1.getValueAt(currentRow, 1));
                c.setName((String) jTable1.getValueAt(currentRow, 2));
                SimpleDateFormat format1 = new SimpleDateFormat(DD_M_MYYYY1);
                Calendar cal1 = Calendar.getInstance();
                cal1.setTime(format1.parse((String) jTable1.getValueAt(currentRow, 3)));
                c.setBirthday(cal1);
                c.setStreetnumber((String) jTable1.getValueAt(currentRow, 4));
                c.setZipcode((String) jTable1.getValueAt(currentRow, 5));
                c.setCity((String) jTable1.getValueAt(currentRow, 6));
                c.setCountry((String) jTable1.getValueAt(currentRow, 7));
                pi.updateCustomer(c.getId(), c.getName(), c.getSurname(), c.getAdress(), c.getStreetnumber(), c.getZipcode(), c.getCity(), c.getCountry(), c.getBirthday());
            } catch (ParseException ex) {
                ErrorWindow s = new ErrorWindow(WRONG_CALENDAR_FORMAT);
            }
        }
        dispose();
        CustomersList s = new CustomersList(pi);
        s.setVisible(true);
    }//GEN-LAST:event_editCustomerActionPerformed
    private static final String DD_M_MYYYY1 = "dd.MM.yyyy";

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomersEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomersEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomersEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomersEdit.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton editCustomer;
    private javax.swing.JButton exitButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
